from typing import Protocol

from app.domain.change.models import GitOpsStatus, PullRequest, ReviewState


class GitChangeProvider(Protocol):
    """Create and observe only. Intentionally has no merge/approve capability."""

    async def read_base_revision(self) -> str: ...

    async def read_file(self, path: str, revision: str) -> str: ...

    async def create_branch(self, branch: str, source_revision: str) -> None: ...

    async def commit_changes(self, branch: str, files: dict[str, str], message: str) -> str: ...

    async def create_pull_request(self, branch: str, title: str, body: str) -> PullRequest: ...

    async def find_pull_request(self, branch: str, change_id: str) -> PullRequest | None: ...

    async def get_pull_request(self, pull_request_id: str) -> PullRequest: ...

    async def get_review_state(self, pull_request_id: str) -> ReviewState: ...

    async def resolve_revision(self, revision: str) -> str: ...


class GitOpsReconciler(Protocol):
    """Read-only GitOps controller boundary. No sync or cluster mutation methods."""

    async def get_application_status(self, application_ref: str) -> GitOpsStatus: ...

    async def refresh(self, application_ref: str) -> None: ...


class ChangeVerifier(Protocol):
    async def verify(self, incident_id: str, verification_profile_ref: str) -> bool: ...
