"""initial schema

Revision ID: 3bdc21ee176f
Revises:
Create Date: 2026-07-22 14:06:50.983929
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

revision: str = '3bdc21ee176f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('environments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_environments')),
    sa.UniqueConstraint('code', name=op.f('uq_environments_code')),
    sa.UniqueConstraint('name', name=op.f('uq_environments_name'))
    )
    op.create_table('hosts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('environment_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('mock_behavior', sa.String(length=20), nullable=False),
    sa.Column('last_status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['environment_id'], ['environments.id'], name=op.f('fk_hosts_environment_id_environments')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_hosts')),
    sa.UniqueConstraint('environment_id', 'name', name=op.f('uq_hosts_environment_id'))
    )
    op.create_index(op.f('ix_hosts_environment_id'), 'hosts', ['environment_id'], unique=False)
    op.create_table('operation_tasks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('environment_id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.Enum('START', 'STOP', 'STATUS', 'INSPECT', name='operationaction'), nullable=False),
    sa.Column('scope', sa.Enum('ALL', 'SERVICE', 'SERVICE_HOSTS', 'HOST', 'HOSTS', name='operationscope'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'SUCCEEDED', 'PARTIALLY_SUCCEEDED', 'FAILED', 'TIMED_OUT', 'CANCELLED', 'REJECTED', name='taskstatus'), nullable=False),
    sa.Column('requested_by', sa.String(length=80), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['environment_id'], ['environments.id'], name=op.f('fk_operation_tasks_environment_id_environments')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_operation_tasks'))
    )
    op.create_index(op.f('ix_operation_tasks_environment_id'), 'operation_tasks', ['environment_id'], unique=False)
    op.create_index(op.f('ix_operation_tasks_status'), 'operation_tasks', ['status'], unique=False)
    op.create_table('services',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('environment_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('service_type', sa.String(length=40), nullable=False),
    sa.Column('is_middleware', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['environment_id'], ['environments.id'], name=op.f('fk_services_environment_id_environments')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_services')),
    sa.UniqueConstraint('environment_id', 'name', name=op.f('uq_services_environment_id'))
    )
    op.create_index(op.f('ix_services_environment_id'), 'services', ['environment_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('task_id', sa.String(length=36), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('actor', sa.String(length=80), nullable=False),
    sa.Column('message', sa.String(length=255), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['operation_tasks.id'], name=op.f('fk_audit_logs_task_id_operation_tasks')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index(op.f('ix_audit_logs_event_type'), 'audit_logs', ['event_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_task_id'), 'audit_logs', ['task_id'], unique=False)
    op.create_table('operation_targets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('service_id', sa.String(length=36), nullable=False),
    sa.Column('host_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SUCCEEDED', 'FAILED', 'TIMED_OUT', name='targetstatus'), nullable=False),
    sa.Column('output', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['host_id'], ['hosts.id'], name=op.f('fk_operation_targets_host_id_hosts')),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], name=op.f('fk_operation_targets_service_id_services')),
    sa.ForeignKeyConstraint(['task_id'], ['operation_tasks.id'], name=op.f('fk_operation_targets_task_id_operation_tasks')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_operation_targets')),
    sa.UniqueConstraint('task_id', 'service_id', 'host_id', name=op.f('uq_operation_targets_task_id'))
    )
    op.create_index(op.f('ix_operation_targets_host_id'), 'operation_targets', ['host_id'], unique=False)
    op.create_index(op.f('ix_operation_targets_service_id'), 'operation_targets', ['service_id'], unique=False)
    op.create_index(op.f('ix_operation_targets_task_id'), 'operation_targets', ['task_id'], unique=False)
    op.create_table('service_deployments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('service_id', sa.String(length=36), nullable=False),
    sa.Column('host_id', sa.String(length=36), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['host_id'], ['hosts.id'], name=op.f('fk_service_deployments_host_id_hosts')),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], name=op.f('fk_service_deployments_service_id_services')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_service_deployments')),
    sa.UniqueConstraint('service_id', 'host_id', name=op.f('uq_service_deployments_service_id'))
    )
    op.create_index(op.f('ix_service_deployments_host_id'), 'service_deployments', ['host_id'], unique=False)
    op.create_index(op.f('ix_service_deployments_service_id'), 'service_deployments', ['service_id'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # Dropping each table also drops its indexes. Explicitly dropping foreign-key
    # support indexes first is invalid on MySQL.
    op.drop_table('service_deployments')
    op.drop_table('operation_targets')
    op.drop_table('audit_logs')
    op.drop_table('services')
    op.drop_table('operation_tasks')
    op.drop_table('hosts')
    op.drop_table('environments')
