from typing import Protocol


class McpResourceReader(Protocol):
    def incident(self, incident_id: str) -> dict[str, object]: ...

    def evidence(self, incident_id: str) -> list[dict[str, object]]: ...

    def timeline(self, incident_id: str) -> list[dict[str, object]]: ...

    def knowledge(self, incident_id: str) -> dict[str, object]: ...
